### ISSUE TITLE
Compose wrong env name

### ISSUE THREAD

**Issue by krzystooof** [flaviostutz/ceph-osd#3]
Considering `osd` configuration there is `PEER_MONITOR_HOSTS` which I believe should be named `MONITOR_HOSTS`.
Log when env name is  `PEER_MONITOR_HOSTS` (only osd3 up) :
```
osd3_1   | Defining default values for ENVs...
osd3_1   | MONITOR_HOSTS must be defined
ceph_osd3_1 exited with code 1
```
Log when env name is  `MONITOR_HOSTS (only osd3 up)`:
```
osd3_1   | Defining default values for ENVs...
osd3_1   | Creating ceph.conf...
osd3_1   | [global]
osd3_1   | auth cluster required = cephx
osd3_1   | auth service required = cephx
osd3_1   | auth client required = cephx
osd3_1   | osd journal size = 1024
osd3_1   | osd pool default size = 3  # Write an object n times.
osd3_1   | osd pool default min size = 2 # Allow writing n copies in a degraded state.
osd3_1   | osd pool default pg num = 64
osd3_1   | osd crush chooseleaf type = 1
osd3_1   | mon host = :16789
osd3_1   | Retrieving keyring for connecting to monitors...
osd3_1   | Retrieving monitor key from ETCD...
osd3_1   | Error:  client: etcd cluster is unavailable or misconfigured; error #0: dial tcp :12379: connect: connection refused
osd3_1   | 
osd3_1   | error #0: dial tcp :12379: connect: connection refused
osd3_1   | 
osd3_1   | Retrying in 1s...
osd3_1   | Retrieving monitor key from ETCD...
osd3_1   | Error:  client: etcd cluster is unavailable or misconfigured; error #0: dial tcp :12379: connect: connection refused
osd3_1   | 
osd3_1   | error #0: dial tcp :12379: connect: connection refused
osd3_1   | 
osd3_1   | Retrying in 1s...
```

**Comment by krzystooof** [comment]
"Fixed" `docker-compose.yml`:

```
version: '3.5'

services:

  etcd0:
    image: quay.io/coreos/etcd
    ports:
      - 12379:2379
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://${HOST_IP}:12379

  mon0:
    image: flaviostutz/ceph-monitor
    pid: host
    ports:
      - 16789:6789
    environment:
      - CREATE_CLUSTER=true
      - ETCD_URL=http://${HOST_IP}:12379
      - MONITOR_ADVERTISE_IP=${HOST_IP}
      - MONITOR_ADVERTISE_PORT=16789

  osd1:
    build: .
    network_mode: host
    pid: host
    environment:
      - LOG_LEVEL=0
      - MONITOR_HOSTS=${HOST_IP}:16789
      - ETCD_URL=http://${HOST_IP}:12379
      # - OSD_PUBLIC_IP=${HOST_IP}
      # - OSD_CLUSTER_IP=${HOST_IP}
    volumes:
      - /mnt/osd1-sda:/var/lib/ceph/osd

  osd2:
    build: .
    network_mode: host
    pid: host
    environment:
      - MONITOR_HOSTS=${HOST_IP}:16789
      - ETCD_URL=http://${HOST_IP}:12379
    volumes:
      - /mnt/osd2-sdb:/var/lib/ceph/osd

  osd3:
    build: .
    network_mode: host
    pid: host
    environment:
      - MONITOR_HOSTS=${HOST_IP}:16789
      - ETCD_URL=http://${HOST_IP}:12379
    volumes:
      - /mnt/osd3-sdc:/var/lib/ceph/osd
```

**Comment by krzystooof** [comment]
I haven't noticed that the compose file in repo is quite different from the one at Dockerhub. 
For everyone wondering about the source of upper `docker-compose.yml` [here it is](https://hub.docker.com/r/flaviostutz/ceph-osd).

**Comment by flaviostutz** [comment]
Thanks! Which docker-compose is the correct one? I got confused.
Please send a PR or open another issue in order to fix the wrong documentation. Thanks again!

**Comment by krzystooof** [comment]
That is a compose from your [docker hub](https://hub.docker.com/r/flaviostutz/ceph-osd) README:
```
version: '3.5'

services:

  etcd0:
    image: quay.io/coreos/etcd
    ports:
      - 12379:2379
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://${HOST_IP}:12379

  mon0:
    image: flaviostutz/ceph-monitor
    pid: host
    ports:
      - 16789:6789
    environment:
      - CREATE_CLUSTER=true
      - ETCD_URL=http://${HOST_IP}:12379
      - MONITOR_ADVERTISE_IP=${HOST_IP}
      - MONITOR_ADVERTISE_PORT=16789

  osd1:
    build: .
    network_mode: host
    pid: host
    environment:
      - LOG_LEVEL=0
      - PEER_MONITOR_HOSTS=${HOST_IP}:16789
      - ETCD_URL=http://${HOST_IP}:12379
      # - OSD_PUBLIC_IP=${HOST_IP}
      # - OSD_CLUSTER_IP=${HOST_IP}
    volumes:
      - /mnt/osd1-sda:/var/lib/ceph/osd

  osd2:
    build: .
    network_mode: host
    pid: host
    environment:
      - PEER_MONITOR_HOSTS=${HOST_IP}:16789
      - ETCD_URL=http://${HOST_IP}:12379
    volumes:
      - /mnt/osd2-sdb:/var/lib/ceph/osd

  osd3:
    build: .
    network_mode: host
    pid: host
    environment:
      - PEER_MONITOR_HOSTS=${HOST_IP}:16789
      - ETCD_URL=http://${HOST_IP}:12379
    volumes:
      - /mnt/osd3-sdc:/var/lib/ceph/osd
```
It is using `PEER_MONITOR_HOSTS` instead of `MONITOR_HOSTS`. I thought that this compose is same as compose here on GitHub, but it is not, so I closed issue. You should update compose in docker hub readme or at least change env names.
